subscribers:

  camera_topics:
    - camera_front/color/image_raw
    - camera_left/color/image_raw
    - camera_right/color/image_raw
    - camera_rear/color/image_raw
    #- camera_up/color/image_raw
  queue_size: 10

publishers:

  object_detector:
    topic: found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: detection_image
    queue_size: 1
    latch: true
  
  detection_depth:
    topic: detection_depth
    queue_size: 1
    latch: true

  detected_object:
    topic: detected_object #subT added
    queue_size: 10
    latch: true
