yolo_trt_model:
  serialized_file:
    name: stair_detection.engine #batch1
  detection_classes:
    names:
      - Stairway
  detect_thresh: # using F1 score metric to testset+KY+prelim
    value: 
      - 0.85
  IoU_thresh:
    value: 0.4
