yolo_trt_model:
  serialized_file:
    name: sep20_7cls_1batch.engine #batch1
  detection_classes:
    names:
      - Survivor
      - Helmet
      - Backpack
      - Drill
      - Fire Extinguisher
      - Rope
      - Cube
  detect_thresh: # using F1 score metric to testset+KY+prelim
    value: 
      - 0.5
      - 0.65
      - 0.55
      - 0.55
      - 0.53
      - 0.45
      - 0.91
  IoU_thresh:
    value: 0.4
