subscribers:

  camera_topics:
    name: 
      - camera_front/color/image_raw #_rotated
      - camera_left/color/image_raw
      - camera_right/color/image_raw
      - camera_up/color/image_raw
      - camera_rear/color/image_raw
    queue_size: 5

publishers:

  detection_image:
    topic: detection_image #/compressed
    queue_size: 1
    latch: true
    resize_scale: 0.25
    enable: true

  detected_object:
    topic: detected_object_raw #subT added
    queue_size: 20
    latch: true
