subscribers:

  camera_topics:
    name: 
      - boson/image_raw
    queue_size: 5

publishers:

  detection_image:
    topic: thermal/detection_image
    queue_size: 1
    latch: true
    enable: true

  detected_object:
    topic: thermal/detected_object_raw #subT added
    queue_size: 5
    latch: true
    